### ISSUE TITLE
Update ohms.html

### ISSUE THREAD

**Issue by timmmmyboy** [libmanuk/SampleOHMSCache#2]
Would you all like to update the main page to link to the new examples 4-7? Just checking before we include this in our Reclaim Hosting installer. We'll also need a Release tagged in this repo.

**Comment by libmanuk** [comment]
Thanks for alerting me to this issue.  I have edited the HTML to set links for the newly added examples and also completed a new release.

**Comment by timmmmyboy** [comment]
Excellent, thanks!
